//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacontrol_PDV.tae_diestel_new {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pagoexpress.com.mx/pxUniversal", ConfigurationName="tae_diestel_new.PxUniversalSoap")]
    public interface PxUniversalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cCampo[]))]
        Farmacontrol_PDV.tae_diestel_new.cCampo[] Info(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Info", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> InfoAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Ejecuta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cCampo[]))]
        Farmacontrol_PDV.tae_diestel_new.cCampo[] Ejecuta(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Ejecuta", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> EjecutaAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Reversa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cCampo[]))]
        Farmacontrol_PDV.tae_diestel_new.cCampo[] Reversa(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Reversa", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> ReversaAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cCampo[]))]
        Farmacontrol_PDV.tae_diestel_new.cCampo[] Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pagoexpress.com.mx/pxUniversal/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> TestAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pagoexpress.com.mx/pxUniversal")]
    public partial class cCampo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCampoField;
        
        private eTipo iTipoField;
        
        private int iLongitudField;
        
        private int iClaseField;
        
        private object sValorField;
        
        private bool bEncriptadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sCampo {
            get {
                return this.sCampoField;
            }
            set {
                this.sCampoField = value;
                this.RaisePropertyChanged("sCampo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public eTipo iTipo {
            get {
                return this.iTipoField;
            }
            set {
                this.iTipoField = value;
                this.RaisePropertyChanged("iTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int iLongitud {
            get {
                return this.iLongitudField;
            }
            set {
                this.iLongitudField = value;
                this.RaisePropertyChanged("iLongitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iClase {
            get {
                return this.iClaseField;
            }
            set {
                this.iClaseField = value;
                this.RaisePropertyChanged("iClase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object sValor {
            get {
                return this.sValorField;
            }
            set {
                this.sValorField = value;
                this.RaisePropertyChanged("sValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool bEncriptado {
            get {
                return this.bEncriptadoField;
            }
            set {
                this.bEncriptadoField = value;
                this.RaisePropertyChanged("bEncriptado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pagoexpress.com.mx/pxUniversal")]
    public enum eTipo {
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NM,
        
        /// <remarks/>
        FD,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        ND,
        
        /// <remarks/>
        PW,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PxUniversalSoapChannel : Farmacontrol_PDV.tae_diestel_new.PxUniversalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PxUniversalSoapClient : System.ServiceModel.ClientBase<Farmacontrol_PDV.tae_diestel_new.PxUniversalSoap>, Farmacontrol_PDV.tae_diestel_new.PxUniversalSoap {
        
        public PxUniversalSoapClient() {
        }
        
        public PxUniversalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PxUniversalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PxUniversalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PxUniversalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Farmacontrol_PDV.tae_diestel_new.cCampo[] Info(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.Info(cArrayCampos);
        }
        
        public System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> InfoAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.InfoAsync(cArrayCampos);
        }
        
        public Farmacontrol_PDV.tae_diestel_new.cCampo[] Ejecuta(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.Ejecuta(cArrayCampos);
        }
        
        public System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> EjecutaAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.EjecutaAsync(cArrayCampos);
        }
        
        public Farmacontrol_PDV.tae_diestel_new.cCampo[] Reversa(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.Reversa(cArrayCampos);
        }
        
        public System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> ReversaAsync(Farmacontrol_PDV.tae_diestel_new.cCampo[] cArrayCampos) {
            return base.Channel.ReversaAsync(cArrayCampos);
        }
        
        public Farmacontrol_PDV.tae_diestel_new.cCampo[] Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<Farmacontrol_PDV.tae_diestel_new.cCampo[]> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
