//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacontrol_PDV.ACP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="ACP-CFDIPortType", Namespace="urn:acpcfdi", ConfigurationName="ACP.ACPCFDIPortType")]
    public interface ACPCFDIPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#consultar_folios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultConsultar_folios consultar_folios(string user, string password, string servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#timbrado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultTimbrado timbrado(string user, string password, string cfdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#timbrado3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultTimbrado timbrado3(string user, string password, string archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpfdi#validar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultValidar validar(string user, string password, string cfdi, string path, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpfdi#consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultConsultar resultado_validacion(string user, string password, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#registrarTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultRegistrarTicket registrarTicket(string user, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#consultarTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultConsultarTicket consultarTicket(string user, string password, string codigo, decimal importe, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#timbrarTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultTimbrarTickets timbrarTickets(string user, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#registrarClienteTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultRegistrarClienteTickets registrarClienteTickets(string user, string password, string identificador, string rfc, string nombre, string calle, string no_exterior, string no_interior, string colonia, string localidad, string referencia, string municipio, string estado, string pais, string codigo_postal);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#generarPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultGenerarPdf generarPdf(string user, string password, string cfdi64, int identificador_factura, string serie, int servicio, bool cancelado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:acpcfdi#enviarCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(archivosDetail))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacontrol_PDV.ACP.resultEnviarCorreo enviarCorreo(string user, string password, int servicio, string uuid, string destinatario);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultConsultar_folios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        private int foliosField;
        
        private string fecha_vencimientoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
                this.RaisePropertyChanged("folios");
            }
        }
        
        /// <remarks/>
        public string fecha_vencimiento {
            get {
                return this.fecha_vencimientoField;
            }
            set {
                this.fecha_vencimientoField = value;
                this.RaisePropertyChanged("fecha_vencimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultEnviarCorreo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultGenerarPdf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        private string pdfField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultRegistrarClienteTickets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        private int identificadorField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
                this.RaisePropertyChanged("identificador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultTimbrarTickets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        private string cfdiField;
        
        private string pdfField;
        
        private string uuidField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                this.cfdiField = value;
                this.RaisePropertyChanged("cfdi");
            }
        }
        
        /// <remarks/>
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class arrayCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificadorField;
        
        private string rfcField;
        
        private string nombreField;
        
        private string calleField;
        
        private string no_exteriorField;
        
        private string no_interiorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string referenciaField;
        
        private string municipioField;
        
        private string estadoField;
        
        private string paisField;
        
        private string codigo_postalField;
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
                this.RaisePropertyChanged("identificador");
            }
        }
        
        /// <remarks/>
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public string calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
                this.RaisePropertyChanged("calle");
            }
        }
        
        /// <remarks/>
        public string no_exterior {
            get {
                return this.no_exteriorField;
            }
            set {
                this.no_exteriorField = value;
                this.RaisePropertyChanged("no_exterior");
            }
        }
        
        /// <remarks/>
        public string no_interior {
            get {
                return this.no_interiorField;
            }
            set {
                this.no_interiorField = value;
                this.RaisePropertyChanged("no_interior");
            }
        }
        
        /// <remarks/>
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
                this.RaisePropertyChanged("colonia");
            }
        }
        
        /// <remarks/>
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
                this.RaisePropertyChanged("municipio");
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        public string codigo_postal {
            get {
                return this.codigo_postalField;
            }
            set {
                this.codigo_postalField = value;
                this.RaisePropertyChanged("codigo_postal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class archivosDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fecha_emisionField;
        
        private decimal importeField;
        
        private string uuidField;
        
        private string cfdiField;
        
        private string pdfField;
        
        /// <remarks/>
        public string fecha_emision {
            get {
                return this.fecha_emisionField;
            }
            set {
                this.fecha_emisionField = value;
                this.RaisePropertyChanged("fecha_emision");
            }
        }
        
        /// <remarks/>
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                this.cfdiField = value;
                this.RaisePropertyChanged("cfdi");
            }
        }
        
        /// <remarks/>
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class arrayTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int cuentaField;
        
        private string fechaField;
        
        private int folioField;
        
        private int statusField;
        
        private decimal importeField;
        
        private decimal saldoField;
        
        private string metodo_pagoField;
        
        private string numero_cuentaField;
        
        private string codigoField;
        
        private int total_partesField;
        
        private archivosDetail[] archivosField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public int cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        public int folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        /// <remarks/>
        public string metodo_pago {
            get {
                return this.metodo_pagoField;
            }
            set {
                this.metodo_pagoField = value;
                this.RaisePropertyChanged("metodo_pago");
            }
        }
        
        /// <remarks/>
        public string numero_cuenta {
            get {
                return this.numero_cuentaField;
            }
            set {
                this.numero_cuentaField = value;
                this.RaisePropertyChanged("numero_cuenta");
            }
        }
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public int total_partes {
            get {
                return this.total_partesField;
            }
            set {
                this.total_partesField = value;
                this.RaisePropertyChanged("total_partes");
            }
        }
        
        /// <remarks/>
        public archivosDetail[] archivos {
            get {
                return this.archivosField;
            }
            set {
                this.archivosField = value;
                this.RaisePropertyChanged("archivos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class detalleConsultarTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private arrayTicket ticketField;
        
        private arrayCliente clienteField;
        
        /// <remarks/>
        public arrayTicket ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        public arrayCliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultConsultarTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        private detalleConsultarTicket resultadosField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public detalleConsultarTicket resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
                this.RaisePropertyChanged("resultados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultRegistrarTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class detalleValidacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estructuraField;
        
        private string estructuraTextoField;
        
        private int selloCFDIField;
        
        private string selloCFDITextoField;
        
        private int selloSATField;
        
        private string selloSATTextoField;
        
        private string respuestaTextoField;
        
        /// <remarks/>
        public int estructura {
            get {
                return this.estructuraField;
            }
            set {
                this.estructuraField = value;
                this.RaisePropertyChanged("estructura");
            }
        }
        
        /// <remarks/>
        public string estructuraTexto {
            get {
                return this.estructuraTextoField;
            }
            set {
                this.estructuraTextoField = value;
                this.RaisePropertyChanged("estructuraTexto");
            }
        }
        
        /// <remarks/>
        public int selloCFDI {
            get {
                return this.selloCFDIField;
            }
            set {
                this.selloCFDIField = value;
                this.RaisePropertyChanged("selloCFDI");
            }
        }
        
        /// <remarks/>
        public string selloCFDITexto {
            get {
                return this.selloCFDITextoField;
            }
            set {
                this.selloCFDITextoField = value;
                this.RaisePropertyChanged("selloCFDITexto");
            }
        }
        
        /// <remarks/>
        public int selloSAT {
            get {
                return this.selloSATField;
            }
            set {
                this.selloSATField = value;
                this.RaisePropertyChanged("selloSAT");
            }
        }
        
        /// <remarks/>
        public string selloSATTexto {
            get {
                return this.selloSATTextoField;
            }
            set {
                this.selloSATTextoField = value;
                this.RaisePropertyChanged("selloSATTexto");
            }
        }
        
        /// <remarks/>
        public string respuestaTexto {
            get {
                return this.respuestaTextoField;
            }
            set {
                this.respuestaTextoField = value;
                this.RaisePropertyChanged("respuestaTexto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class detalleConsultar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string mensajeField;
        
        private int numDelayField;
        
        private string uidField;
        
        private string urlField;
        
        private string fechaEnvioField;
        
        private string fechaInicioValidacionField;
        
        private string fechaTerminoValidacionField;
        
        private detalleValidacion validacionField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int numDelay {
            get {
                return this.numDelayField;
            }
            set {
                this.numDelayField = value;
                this.RaisePropertyChanged("numDelay");
            }
        }
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public string fechaEnvio {
            get {
                return this.fechaEnvioField;
            }
            set {
                this.fechaEnvioField = value;
                this.RaisePropertyChanged("fechaEnvio");
            }
        }
        
        /// <remarks/>
        public string fechaInicioValidacion {
            get {
                return this.fechaInicioValidacionField;
            }
            set {
                this.fechaInicioValidacionField = value;
                this.RaisePropertyChanged("fechaInicioValidacion");
            }
        }
        
        /// <remarks/>
        public string fechaTerminoValidacion {
            get {
                return this.fechaTerminoValidacionField;
            }
            set {
                this.fechaTerminoValidacionField = value;
                this.RaisePropertyChanged("fechaTerminoValidacion");
            }
        }
        
        /// <remarks/>
        public detalleValidacion validacion {
            get {
                return this.validacionField;
            }
            set {
                this.validacionField = value;
                this.RaisePropertyChanged("validacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultConsultar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string subcodigoField;
        
        private string mensajeField;
        
        private detalleConsultar detalleField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string subcodigo {
            get {
                return this.subcodigoField;
            }
            set {
                this.subcodigoField = value;
                this.RaisePropertyChanged("subcodigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public detalleConsultar detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class detalleValidar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string mensajeField;
        
        private string uUIDField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultValidar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private int subcodigoField;
        
        private string mensajeField;
        
        private detalleValidar detalleField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public int subcodigo {
            get {
                return this.subcodigoField;
            }
            set {
                this.subcodigoField = value;
                this.RaisePropertyChanged("subcodigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public detalleValidar detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:acpcfdi")]
    public partial class resultTimbrado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string cfdiField;
        
        private string pdfField;
        
        private string statusField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                this.cfdiField = value;
                this.RaisePropertyChanged("cfdi");
            }
        }
        
        /// <remarks/>
        public string pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
                this.RaisePropertyChanged("pdf");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ACPCFDIPortTypeChannel : Farmacontrol_PDV.ACP.ACPCFDIPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACPCFDIPortTypeClient : System.ServiceModel.ClientBase<Farmacontrol_PDV.ACP.ACPCFDIPortType>, Farmacontrol_PDV.ACP.ACPCFDIPortType {
        
        public ACPCFDIPortTypeClient() {
        }
        
        public ACPCFDIPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACPCFDIPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACPCFDIPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACPCFDIPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Farmacontrol_PDV.ACP.resultConsultar_folios consultar_folios(string user, string password, string servicio) {
            return base.Channel.consultar_folios(user, password, servicio);
        }
        
        public Farmacontrol_PDV.ACP.resultTimbrado timbrado(string user, string password, string cfdi) {
            return base.Channel.timbrado(user, password, cfdi);
        }
        
        public Farmacontrol_PDV.ACP.resultTimbrado timbrado3(string user, string password, string archivo) {
            return base.Channel.timbrado3(user, password, archivo);
        }
        
        public Farmacontrol_PDV.ACP.resultValidar validar(string user, string password, string cfdi, string path, string name) {
            return base.Channel.validar(user, password, cfdi, path, name);
        }
        
        public Farmacontrol_PDV.ACP.resultConsultar resultado_validacion(string user, string password, string uuid) {
            return base.Channel.resultado_validacion(user, password, uuid);
        }
        
        public Farmacontrol_PDV.ACP.resultRegistrarTicket registrarTicket(string user, string password, string xml) {
            return base.Channel.registrarTicket(user, password, xml);
        }
        
        public Farmacontrol_PDV.ACP.resultConsultarTicket consultarTicket(string user, string password, string codigo, decimal importe, string rfc) {
            return base.Channel.consultarTicket(user, password, codigo, importe, rfc);
        }
        
        public Farmacontrol_PDV.ACP.resultTimbrarTickets timbrarTickets(string user, string password, string xml) {
            return base.Channel.timbrarTickets(user, password, xml);
        }
        
        public Farmacontrol_PDV.ACP.resultRegistrarClienteTickets registrarClienteTickets(string user, string password, string identificador, string rfc, string nombre, string calle, string no_exterior, string no_interior, string colonia, string localidad, string referencia, string municipio, string estado, string pais, string codigo_postal) {
            return base.Channel.registrarClienteTickets(user, password, identificador, rfc, nombre, calle, no_exterior, no_interior, colonia, localidad, referencia, municipio, estado, pais, codigo_postal);
        }
        
        public Farmacontrol_PDV.ACP.resultGenerarPdf generarPdf(string user, string password, string cfdi64, int identificador_factura, string serie, int servicio, bool cancelado) {
            return base.Channel.generarPdf(user, password, cfdi64, identificador_factura, serie, servicio, cancelado);
        }
        
        public Farmacontrol_PDV.ACP.resultEnviarCorreo enviarCorreo(string user, string password, int servicio, string uuid, string destinatario) {
            return base.Channel.enviarCorreo(user, password, servicio, uuid, destinatario);
        }
    }
}
